// Auto-generated by refactor: centralized PlayerPrefs keys.
public static class GameConstants
{
    public const string PrefSkinMenuPosition = "Skin Menu Position";
    public const string PrefHighScore = "High Score";

    // Global rocket movement tuning (per-second units before legacy autoscaling).
    public const float RocketInitialSpeed = 2;
    public const float RocketFinalSpeed = 4;
}
